name: Robot Framework Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install browser
        run: rfbrowser init

      - name: Run Robot Framework tests
        id: tests
        continue-on-error: true
        run: robot -P . --outputdir data/output --xunit report.xml tests

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: data/output/report.xml

      - name: Upload Log HTML Report
        uses: actions/upload-artifact@v4
        with:
          path: |
            data/output/log.html
            data/output/browser/screenshot/*
          retention-days: 1
